/*
 * Aulas professor Maromo.
 */
package br.faculdade.gerenciamentolivros.view;

import br.faculdade.gerenciamentolivros.business.LivroBUS;
import br.faculdade.gerenciamentolivros.entities.Editora;
import br.faculdade.gerenciamentolivros.entities.Livro;
import br.faculdade.gerenciamentolivros.persistence.EditoraDAO;
import br.faculdade.gerenciamentolivros.persistence.LivroDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author maromo
 */
public class LivrosVIEW extends javax.swing.JFrame {

    //Atributo criado para gerenciar um livro.
    Livro livro;
    List<Editora> listaEditora;

    /**
     * Creates new form LivrosVIEW
     */
    public LivrosVIEW() {
        initComponents();
        //Aparência
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivrosVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoLivro = new javax.swing.JLabel();
        lblTituloLivro = new javax.swing.JLabel();
        lblEditora = new javax.swing.JLabel();
        lblDataPublicacao = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        txtIdLivro = new javax.swing.JTextField();
        txtTituloLivro = new javax.swing.JTextField();
        cmbEditora = new javax.swing.JComboBox();
        formatTxtDataPublicacao = new javax.swing.JFormattedTextField();
        txtAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTxtObservacaoes = new javax.swing.JTextPane();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Livros");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblCodigoLivro.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCodigoLivro.setText("Código do Livro:");

        lblTituloLivro.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTituloLivro.setText("Título do Livro:");

        lblEditora.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblEditora.setText("Editora:");

        lblDataPublicacao.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDataPublicacao.setText("Data da Publicação:");

        lblAutor.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAutor.setText("Autor:");

        lblObservacoes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblObservacoes.setText("Observações:");

        txtIdLivro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdLivroFocusLost(evt);
            }
        });

        formatTxtDataPublicacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jScrollPane1.setViewportView(pnlTxtObservacaoes);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/faculdade/gerenciamentolivros/utils/action_add_16xLG.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseClicked(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/faculdade/gerenciamentolivros/utils/LaunchSamplingTarget_8880.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/faculdade/gerenciamentolivros/utils/action_Cancel_16xLG.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirMouseClicked(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/faculdade/gerenciamentolivros/utils/Query_16xLG.png"))); // NOI18N
        btnListar.setText("Listar");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/faculdade/gerenciamentolivros/utils/folder_Closed_16xLG.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoLivro)
                            .addComponent(lblTituloLivro)
                            .addComponent(lblEditora)
                            .addComponent(lblDataPublicacao)
                            .addComponent(lblAutor)
                            .addComponent(lblObservacoes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formatTxtDataPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAutor)
                            .addComponent(txtTituloLivro)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoLivro)
                    .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLivro)
                    .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditora)
                    .addComponent(cmbEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPublicacao)
                    .addComponent(formatTxtDataPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacoes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            EditoraDAO dao = new EditoraDAO();
            listaEditora = dao.listar();
            //usando Lambda para ordenação
            Comparator<Editora> comparator = (e1, e2) -> e1.nomeEditora.compareTo(e2.nomeEditora);
            Collections.sort(listaEditora, comparator);
            //Populando o JComboBox
            for (Editora item : listaEditora) {
                StringBuilder sb = new StringBuilder();
                sb.append(item.nomeEditora).append("  Cod --> ").append(item.idEditora);
                cmbEditora.addItem(String.valueOf(sb.toString()));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LivrosVIEW.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtIdLivroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLivroFocusLost
        try {
            int idLivro = Integer.parseInt(txtIdLivro.getText());
            LivroBUS bus = new LivroBUS();
            livro = bus.buscar(idLivro);
            if (livro.idLivro == 0) {
                //cadastrar
                btnAdicionar.setEnabled(true);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);
                txtIdLivro.setEnabled(false);
            } else {
                //preparar para atualizar ou excluir
                btnAlterar.setEnabled(true);
                btnAdicionar.setEnabled(false);
                txtIdLivro.setEnabled(false);
                //Exibir os dados
                int idEditora = livro.editora.idEditora;
                int i = 0;
                for (Editora item : listaEditora) {
                    if (idEditora == item.idEditora) {
                        break;
                    }
                    i++;
                }
                cmbEditora.setSelectedIndex(i);
                txtTituloLivro.setText(livro.tituloLivro);
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                formatter = formatter.withLocale(getLocale());
                formatTxtDataPublicacao.setText(livro.dataPublicacao.format(formatter));
                txtAutor.setText(livro.autor);
                pnlTxtObservacaoes.setText(livro.observacoes);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_txtIdLivroFocusLost

    private void btnAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseClicked
        // TODO add your handling code here:
        try {
            livro.idLivro = Integer.parseInt(txtIdLivro.getText());
            livro.tituloLivro = txtTituloLivro.getText();
            livro.editora = listaEditora.get(cmbEditora.getSelectedIndex());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            formatter = formatter.withLocale(getLocale());
            livro.dataPublicacao = LocalDate.parse(formatTxtDataPublicacao.getText(), formatter);
            livro.autor = txtAutor.getText();
            livro.observacoes = pnlTxtObservacaoes.getText();
            LivroDAO dao = new LivroDAO();
            dao.inserir(livro);
            JOptionPane.showMessageDialog(null, "Dados gravados com sucesso.");
            tratarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarMouseClicked

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        try {
            livro.idLivro = Integer.parseInt(txtIdLivro.getText());
            livro.tituloLivro = txtTituloLivro.getText();
            livro.editora = listaEditora.get(cmbEditora.getSelectedIndex());
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            formatter = formatter.withLocale(getLocale());
            livro.dataPublicacao = LocalDate.parse(formatTxtDataPublicacao.getText(), formatter);
            livro.autor = txtAutor.getText();
            livro.observacoes = pnlTxtObservacaoes.getText();
            LivroDAO dao = new LivroDAO();
            dao.alterar(livro);
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso.");
            tratarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirMouseClicked
        // TODO add your handling code here:
        try {
            LivroDAO dao = new LivroDAO();
            dao.excluir(livro);
            JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso.");
            tratarControles();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
        // TODO add your handling code here:
        List<Livro>listaLivro;
        LivroBUS bus = new LivroBUS();
        listaLivro = bus.listar();
        ConsultaVIEW telaConsulta = new ConsultaVIEW(listaLivro, listaEditora);
        telaConsulta.setVisible(true);
        telaConsulta.setTitle("Consulta de Livros");
        
    }//GEN-LAST:event_btnListarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cmbEditora;
    private javax.swing.JFormattedTextField formatTxtDataPublicacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCodigoLivro;
    private javax.swing.JLabel lblDataPublicacao;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblTituloLivro;
    private javax.swing.JTextPane pnlTxtObservacaoes;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtIdLivro;
    private javax.swing.JTextField txtTituloLivro;
    // End of variables declaration//GEN-END:variables

    private void tratarControles() {
        txtIdLivro.setEnabled(true);
        txtIdLivro.setText(null);
        txtTituloLivro.setText(null);
        formatTxtDataPublicacao.setText(null);
        cmbEditora.setSelectedIndex(0);
        txtAutor.setText(null);
        pnlTxtObservacaoes.setText(null);
        btnAdicionar.setEnabled(true);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        txtIdLivro.requestFocus();
    }
}
